let data = {
    "msg": "成功",
    "code": "0000",
    "data": {
      "total": 10800,
      "tableData": [{
          "allocNo": "FAGZ339968",
          "policyNo": "ZHANGSAN5",
          "allocName": "",
          "allocType": "逾期总额",
          "allocWay": "手动分案",
          "isAvgAlloc": "是",
          "isSecondAlloc": "0",
          "allocDay": null,
          "policyName": "hmm test2",
          "queueNo": null,
          "riskLevel": "全部",
          "businessCategory": "全部",
          "businessType": "全部",
          "validStartTime": "2018-07-31 16:55:04",
          "validEndTime": null,
          "validFlag": "无效",
          "creator": "田强",
          "createdTime": "2018-07-03 16:56:41",
          "updator": "",
          "updatedTime": null
        }, {
          "allocNo": "FAGZ844900",
          "policyNo": "CSCL156315",
          "allocName": "",
          "allocType": "剩余本金",
          "allocWay": "手动分案",
          "isAvgAlloc": "是",
          "isSecondAlloc": "0",
          "allocDay": null,
          "policyName": "消金类正常C-M1测试",
          "queueNo": "12222",
          "riskLevel": "全部",
          "businessCategory": "消费分期",
          "businessType": "全部",
          "validStartTime": "2018-06-28 09:38:29",
          "validEndTime": "2018-06-28 13:47:30",
          "validFlag": "无效",
          "creator": "田强",
          "createdTime": "2018-06-26 09:39:54",
          "updator": "",
          "updatedTime": null
        }, {
          "allocNo": "FAGZ103486",
          "policyNo": "CSCL156315",
          "allocName": "",
          "allocType": "剩余本金",
          "allocWay": "手动分案",
          "isAvgAlloc": "是",
          "isSecondAlloc": "0",
          "allocDay": null,
          "policyName": "消金类正常C-M1测试",
          "queueNo": "12222",
          "riskLevel": "全部",
          "businessCategory": "消费分期",
          "businessType": "全部",
          "validStartTime": "2018-06-25 15:07:59",
          "validEndTime": null,
          "validFlag": "有效",
          "creator": "田强",
          "createdTime": "2018-06-25 15:09:42",
          "updator": "",
          "updatedTime": null}, {
            "allocNo": "FAGZ103486",
            "policyNo": "CSCL156315",
            "allocName": "",
            "allocType": "剩余本金",
            "allocWay": "手动分案",
            "isAvgAlloc": "是",
            "isSecondAlloc": "0",
            "allocDay": null,
            "policyName": "消金类正常C-M1测试",
            "queueNo": "12222",
            "riskLevel": "全部",
            "businessCategory": "消费分期",
            "businessType": "全部",
            "validStartTime": "2018-06-25 15:07:59",
            "validEndTime": null,
            "validFlag": "有效",
            "creator": "田强",
            "createdTime": "2018-06-25 15:09:42",
            "updator": "",
            "updatedTime": null}, {
              "allocNo": "FAGZ103486",
              "policyNo": "CSCL156315",
              "allocName": "",
              "allocType": "剩余本金",
              "allocWay": "手动分案",
              "isAvgAlloc": "是",
              "isSecondAlloc": "0",
              "allocDay": null,
              "policyName": "消金类正常C-M1测试",
              "queueNo": "12222",
              "riskLevel": "全部",
              "businessCategory": "消费分期",
              "businessType": "全部",
              "validStartTime": "2018-06-25 15:07:59",
              "validEndTime": null,
              "validFlag": "有效",
              "creator": "田强",
              "createdTime": "2018-06-25 15:09:42",
              "updator": "",
              "updatedTime": null}, {
                "allocNo": "FAGZ103486",
                "policyNo": "CSCL156315",
                "allocName": "",
                "allocType": "剩余本金",
                "allocWay": "手动分案",
                "isAvgAlloc": "是",
                "isSecondAlloc": "0",
                "allocDay": null,
                "policyName": "消金类正常C-M1测试",
                "queueNo": "12222",
                "riskLevel": "全部",
                "businessCategory": "消费分期",
                "businessType": "全部",
                "validStartTime": "2018-06-25 15:07:59",
                "validEndTime": null,
                "validFlag": "有效",
                "creator": "田强",
                "createdTime": "2018-06-25 15:09:42",
                "updator": "",
                "updatedTime": null}, {
                  "allocNo": "FAGZ103486",
                  "policyNo": "CSCL156315",
                  "allocName": "",
                  "allocType": "剩余本金",
                  "allocWay": "手动分案",
                  "isAvgAlloc": "是",
                  "isSecondAlloc": "0",
                  "allocDay": null,
                  "policyName": "消金类正常C-M1测试",
                  "queueNo": "12222",
                  "riskLevel": "全部",
                  "businessCategory": "消费分期",
                  "businessType": "全部",
                  "validStartTime": "2018-06-25 15:07:59",
                  "validEndTime": null,
                  "validFlag": "有效",
                  "creator": "田强",
                  "createdTime": "2018-06-25 15:09:42",
                  "updator": "",
                  "updatedTime": null}, {
                    "allocNo": "FAGZ103486",
                    "policyNo": "CSCL156315",
                    "allocName": "",
                    "allocType": "剩余本金",
                    "allocWay": "手动分案",
                    "isAvgAlloc": "是",
                    "isSecondAlloc": "0",
                    "allocDay": null,
                    "policyName": "消金类正常C-M1测试",
                    "queueNo": "12222",
                    "riskLevel": "全部",
                    "businessCategory": "消费分期",
                    "businessType": "全部",
                    "validStartTime": "2018-06-25 15:07:59",
                    "validEndTime": null,
                    "validFlag": "有效",
                    "creator": "田强",
                    "createdTime": "2018-06-25 15:09:42",
                    "updator": "",
                    "updatedTime": null}, {
                      "allocNo": "FAGZ103486",
                      "policyNo": "CSCL156315",
                      "allocName": "",
                      "allocType": "剩余本金",
                      "allocWay": "手动分案",
                      "isAvgAlloc": "是",
                      "isSecondAlloc": "0",
                      "allocDay": null,
                      "policyName": "消金类正常C-M1测试",
                      "queueNo": "12222",
                      "riskLevel": "全部",
                      "businessCategory": "消费分期",
                      "businessType": "全部",
                      "validStartTime": "2018-06-25 15:07:59",
                      "validEndTime": null,
                      "validFlag": "有效",
                      "creator": "田强",
                      "createdTime": "2018-06-25 15:09:42",
                      "updator": "",
                      "updatedTime": null}, {
                        "allocNo": "FAGZ103486",
                        "policyNo": "CSCL156315",
                        "allocName": "",
                        "allocType": "剩余本金",
                        "allocWay": "手动分案",
                        "isAvgAlloc": "是",
                        "isSecondAlloc": "0",
                        "allocDay": null,
                        "policyName": "消金类正常C-M1测试",
                        "queueNo": "12222",
                        "riskLevel": "全部",
                        "businessCategory": "消费分期",
                        "businessType": "全部",
                        "validStartTime": "2018-06-25 15:07:59",
                        "validEndTime": null,
                        "validFlag": "有效",
                        "creator": "田强",
                        "createdTime": "2018-06-25 15:09:42",
                        "updator": "",
                        "updatedTime": null}, {
                          "allocNo": "FAGZ103486",
                          "policyNo": "CSCL156315",
                          "allocName": "",
                          "allocType": "剩余本金",
                          "allocWay": "手动分案",
                          "isAvgAlloc": "是",
                          "isSecondAlloc": "0",
                          "allocDay": null,
                          "policyName": "消金类正常C-M1测试",
                          "queueNo": "12222",
                          "riskLevel": "全部",
                          "businessCategory": "消费分期",
                          "businessType": "全部",
                          "validStartTime": "2018-06-25 15:07:59",
                          "validEndTime": null,
                          "validFlag": "有效",
                          "creator": "田强",
                          "createdTime": "2018-06-25 15:09:42",
                          "updator": "",
                          "updatedTime": null}, {
                            "allocNo": "FAGZ103486",
                            "policyNo": "CSCL156315",
                            "allocName": "",
                            "allocType": "剩余本金",
                            "allocWay": "手动分案",
                            "isAvgAlloc": "是",
                            "isSecondAlloc": "0",
                            "allocDay": null,
                            "policyName": "消金类正常C-M1测试",
                            "queueNo": "12222",
                            "riskLevel": "全部",
                            "businessCategory": "消费分期",
                            "businessType": "全部",
                            "validStartTime": "2018-06-25 15:07:59",
                            "validEndTime": null,
                            "validFlag": "有效",
                            "creator": "田强",
                            "createdTime": "2018-06-25 15:09:42",
                            "updator": "",
                            "updatedTime": null}, {
                              "allocNo": "FAGZ103486",
                              "policyNo": "CSCL156315",
                              "allocName": "",
                              "allocType": "剩余本金",
                              "allocWay": "手动分案",
                              "isAvgAlloc": "是",
                              "isSecondAlloc": "0",
                              "allocDay": null,
                              "policyName": "消金类正常C-M1测试",
                              "queueNo": "12222",
                              "riskLevel": "全部",
                              "businessCategory": "消费分期",
                              "businessType": "全部",
                              "validStartTime": "2018-06-25 15:07:59",
                              "validEndTime": null,
                              "validFlag": "有效",
                              "creator": "田强",
                              "createdTime": "2018-06-25 15:09:42",
                              "updator": "",
                              "updatedTime": null}, {
                                "allocNo": "FAGZ103486",
                                "policyNo": "CSCL156315",
                                "allocName": "",
                                "allocType": "剩余本金",
                                "allocWay": "手动分案",
                                "isAvgAlloc": "是",
                                "isSecondAlloc": "0",
                                "allocDay": null,
                                "policyName": "消金类正常C-M1测试",
                                "queueNo": "12222",
                                "riskLevel": "全部",
                                "businessCategory": "消费分期",
                                "businessType": "全部",
                                "validStartTime": "2018-06-25 15:07:59",
                                "validEndTime": null,
                                "validFlag": "有效",
                                "creator": "田强",
                                "createdTime": "2018-06-25 15:09:42",
                                "updator": "",
                                "updatedTime": null}, {
                                  "allocNo": "FAGZ103486",
                                  "policyNo": "CSCL156315",
                                  "allocName": "",
                                  "allocType": "剩余本金",
                                  "allocWay": "手动分案",
                                  "isAvgAlloc": "是",
                                  "isSecondAlloc": "0",
                                  "allocDay": null,
                                  "policyName": "消金类正常C-M1测试",
                                  "queueNo": "12222",
                                  "riskLevel": "全部",
                                  "businessCategory": "消费分期",
                                  "businessType": "全部",
                                  "validStartTime": "2018-06-25 15:07:59",
                                  "validEndTime": null,
                                  "validFlag": "有效",
                                  "creator": "田强",
                                  "createdTime": "2018-06-25 15:09:42",
                                  "updator": "",
                                  "updatedTime": null}]
    }
  }
export { data }
